In [1]:
import pandas as pd
import numpy as np

## Pandas Series 속성

In [2]:
!which python

/Users/gyp/Documents/venv/bin/python


In [4]:
dic = {'one':1,'two':2,'three':3,'four':4, 'five':5}; dic

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

In [8]:
?pd.Series

In [6]:
obj = pd.Series(dic,name='dic'); obj

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [5]:
print(obj.name) # dic - Series 인스턴스에 대한 이름
print(obj.shape) # (5,) - DataFrame의 행렬 형태를 표시
print(obj.dtypes) # int64 - 행과 열에 대한 데이터 타입을 표시
print(obj.ndim) # 1 - 차원에 대한 정보 표시
print(obj.size) # 5 - 원소들의 갯수
print(obj.ftypes) # int64:dense
print(obj.axes) # [Index(['five', 'four', 'one', 'three', 'two'], dtype='object')] - 행과 열에 대한 축을 접근 표시
print(obj.empty) # False - DataFrame 내부가 없으면 True  원소가 있으면 False
print(obj.strides) # (8,) - 데이터를 구성하는 총 갯수
print(obj.index) # Index(['five', 'four', 'one', 'three', 'two'], dtype='object') - 생성된 행에 대한 index 표시
print(obj.values) # [5 4 1 3 2] - 실제 data를 Numpy 로 변환

dic
(5,)
int64
1
5
int64:dense
[Index(['one', 'two', 'three', 'four', 'five'], dtype='object')]
False
(8,)
Index(['one', 'two', 'three', 'four', 'five'], dtype='object')
[1 2 3 4 5]


/home/raonbit/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: Series.strides is deprecated and will be removed in a future version
  if __name__ == '__main__':


In [7]:
type(obj)

pandas.core.series.Series

In [10]:
print(obj.values)

[1 2 3 4 5]


## Series 생성
### ndarray to Series

In [258]:
print(pd.Series(),'\n')
print(pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e']),'\n')
print(pd.Series(np.random.randn(5)),'\n')

Series([], dtype: float64) 

a    2.049294
b   -0.634283
c    2.211932
d   -0.490323
e   -0.468500
dtype: float64 

0    1.902394
1    0.676254
2    0.741278
3   -0.630790
4    0.220393
dtype: float64 

1


In [20]:
pd.Series(np.random.rand(5), index=['a','b','c','d','e'])

a    0.786582
b    0.772812
c    0.124959
d    0.758482
e    0.323145
dtype: float64

### dict to Series

In [9]:
d = {'b' : 1, 'a' : 0, 'c' : 2}
print(pd.Series(d), '\n')
d = {'a' : 0., 'b' : 1., 'c' : 2.}
print(pd.Series(d), '\n')
print(pd.Series(d, index=['b', 'c', 'd', 'a']), '\n')

b    1
a    0
c    2
dtype: int64 

a    0.0
b    1.0
c    2.0
dtype: float64 

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64 



### scalar to Series

In [10]:
print(pd.Series(5., index=['a', 'b', 'c', 'd', 'e']))

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64


## Series is ndarray-like

In [31]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic)
print(obj,'\n')
obj = pd.Series(dic, name='dic')
print(obj)

one      1
two      2
three    3
four     4
five     5
dtype: int64 

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [32]:
obj[0]

1

In [29]:
obj[:3]

one      1
two      2
three    3
Name: dic, dtype: int64

In [30]:
obj.mean()

3.0

In [33]:
obj.sum()

15

In [34]:
obj[obj > obj.mean()]

four    4
five    5
Name: dic, dtype: int64

In [35]:
obj[[3,2,1]]

four     4
three    3
two      2
Name: dic, dtype: int64

In [36]:
?np.exp

In [38]:
np.exp(obj)

one        2.718282
two        7.389056
three     20.085537
four      54.598150
five     148.413159
Name: dic, dtype: float64

## Series is dict-like

In [39]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic, name='dic')
print(obj)

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [40]:
obj['three']

3

In [41]:
obj[2]

3

In [44]:
obj['three'] = 3.2

In [45]:
obj['three']

3

In [46]:
obj['three'] = 33 # obj['three'] = 3.2 자동 형변환되어 3으로 입력 됨

In [47]:
obj['three']

33

In [49]:
obj.head(n=2)

one    1
two    2
Name: dic, dtype: int64

In [50]:
'three' in obj

True

In [52]:
'six' in obj

False

In [53]:
obj['six']

KeyError: 'six'

In [54]:
obj.get('six', 6) #없을 때 반환할 Default값

6

In [55]:
obj['six'] = obj.get('six', 6)
obj['six']

6

In [57]:
obj

one       1
two       2
three    33
four      4
five      5
six       6
Name: dic, dtype: int64

In [59]:
obj['two':'five']

two       2
three    33
four      4
five      5
Name: dic, dtype: int64

In [60]:
obj['five':'one']

Series([], Name: dic, dtype: int64)

## Series Method : replace

In [61]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic, name='dic')
obj

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [62]:
obj['three'] = 33
obj['three']

33

In [64]:
obj.replace(33,3)

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [65]:
obj

one       1
two       2
three    33
four      4
five      5
Name: dic, dtype: int64

In [66]:
obj.replace(33,3,inplace=True)
obj

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [82]:
obj = obj.replace(3,33)
obj

one       1
two       2
three    33
four      4
five      5
Name: dic, dtype: int64

In [87]:
obj['three':'three'].replace(33,3, inplace=True)
obj

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [85]:
obj['three':'three'].replace(3,33,inplace=True)

## Series Multiindex

In [86]:
obj

one       1
two       2
three    33
four      4
five      5
Name: dic, dtype: int64

In [101]:
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
           ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [93]:
zip[arrays]

TypeError: 'type' object is not subscriptable

In [102]:
zip(*arrays)

In [104]:
tuples = list(zip(*arrays)); print(tuples)

[('bar', 'one'), ('bar', 'two'), ('baz', 'one'), ('baz', 'two'), ('foo', 'one'), ('foo', 'two'), ('qux', 'one'), ('qux', 'two')]


In [106]:
index = pd.MultiIndex.from_tuples(tuples, names=['first','second']); index

MultiIndex(levels=[['bar', 'baz', 'foo', 'qux'], ['one', 'two']],
           labels=[[0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]],
           names=['first', 'second'])

In [107]:
s = pd.Series(np.random.randn(8), index=index)
print(s)

first  second
bar    one       0.044387
       two       0.840425
baz    one       0.655413
       two       0.216927
foo    one      -1.514653
       two      -1.605653
qux    one       2.227348
       two      -0.042185
dtype: float64


In [108]:
s['bar','one']

0.04438712284840146

In [109]:
s['baz','two']

0.21692663312231997

## Series 접근

In [110]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic, name='dic')
print(obj)

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [111]:
obj.get('two')

2

In [112]:
obj.get(2)

3

In [113]:
print(obj.get('six'))
print(obj.get('six', 6))

None
6


In [114]:
obj.astype('float64')

one      1.0
two      2.0
three    3.0
four     4.0
five     5.0
Name: dic, dtype: float64

In [115]:
obj

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [118]:
obj = obj.astype('float64')
obj

one      1.0
two      2.0
three    3.0
four     4.0
five     5.0
Name: dic, dtype: float64

In [119]:
obj.at

In [125]:
obj.at['two']

2.0

In [121]:
obj.iat[2]

3.0

In [126]:
obj.loc['four':]

four    4.0
five    5.0
Name: dic, dtype: float64

In [127]:
obj.iloc[4:]

five    5.0
Name: dic, dtype: float64

In [128]:
obj.ix[4]

/Users/gyp/Documents/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


5.0

In [129]:
obj.ix['four']

/Users/gyp/Documents/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


4.0

In [132]:
obj.at[2]

ValueError: At based indexing on an non-integer index can only have non-integer indexers

In [133]:
obj.iat['two']

ValueError: iAt based indexing can only have integer indexers

In [100]:
obj.loc[4]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [4] of <class 'int'>

In [101]:
obj.iloc['two']

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [two] of <class 'str'>

In [134]:
obj.iloc[2] = 3
obj

one      1.0
two      2.0
three    3.0
four     4.0
five     5.0
Name: dic, dtype: float64

In [135]:
dic = {5:1,4:2,3:3,2:4,1:5}
obj2 = pd.Series(dic, name='dic')
print(obj2)

5    1
4    2
3    3
2    4
1    5
Name: dic, dtype: int64


In [136]:
obj2.ix[1]

/Users/gyp/Documents/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


5

In [137]:
obj2.loc[1]

5

## Series 메소드 : items(), keys(), to_dict(), tolist(), to_json()

In [138]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic, name='dic')
print(obj)
obj.items()

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [136]:
list(obj.items())

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)]

In [137]:
tuple(obj.items())

(('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5))

In [138]:
dict(obj.items())

{'five': 5, 'four': 4, 'one': 1, 'three': 3, 'two': 2}

In [145]:
[(k,v) for k,v in obj.items()]

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)]

In [146]:
obj.value()

AttributeError: 'Series' object has no attribute 'value'

In [147]:
obj.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [148]:
type(obj.index)

pandas.core.indexes.base.Index

In [149]:
obj.keys() # obj.index 와 동일

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [150]:
type(obj.keys())

pandas.core.indexes.base.Index

In [151]:
obj.tolist()

[1, 2, 3, 4, 5]

In [157]:
obj.to_dict()

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

In [158]:
obj.to_json()

'{"one":1,"two":2,"three":3,"four":4,"five":5}'

## Series 메소드 : sort_values()

In [159]:
dic = {'one':1,'four':4,'three':3,'two':2,'five':5}
obj = pd.Series(dic, name='dic')
print(obj)

one      1
four     4
three    3
two      2
five     5
Name: dic, dtype: int64


In [160]:
obj.sort_values()

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64

In [161]:
print(obj)

one      1
four     4
three    3
two      2
five     5
Name: dic, dtype: int64


In [162]:
obj.sort_values(inplace=True)
print(obj)

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [163]:
obj.sort_values(ascending=False, inplace=True)
print(obj)

five     5
four     4
three    3
two      2
one      1
Name: dic, dtype: int64


In [166]:
obj.sort_index(ascending=False)

two      2
three    3
one      1
four     4
five     5
Name: dic, dtype: int64

## Series 산술 연산
### Series, scalar 연산

In [167]:
dic = {'one':1,'two':2,'three':3,'four':4,'five':5}
obj = pd.Series(dic, name='dic')
print(obj)

one      1
two      2
three    3
four     4
five     5
Name: dic, dtype: int64


In [168]:
print(obj+1)

one      2
two      3
three    4
four     5
five     6
Name: dic, dtype: int64


In [169]:
print(obj-1)

one      0
two      1
three    2
four     3
five     4
Name: dic, dtype: int64


In [170]:
print(obj*2)

one       2
two       4
three     6
four      8
five     10
Name: dic, dtype: int64


In [171]:
print(obj/2)

one      0.5
two      1.0
three    1.5
four     2.0
five     2.5
Name: dic, dtype: float64


In [172]:
print(obj//2)

one      0
two      1
three    1
four     2
five     2
Name: dic, dtype: int64


In [173]:
print(obj%2)

one      1
two      0
three    1
four     0
five     1
Name: dic, dtype: int64


### Series 간 연산

In [174]:
obj = pd.Series([1,2,3,4,5])
obj2 = pd.Series([6,7,8,9])
print(obj);print(obj.size);print();
print(obj2);print(obj2.size)

0    1
1    2
2    3
3    4
4    5
dtype: int64
5

0    6
1    7
2    8
3    9
dtype: int64
4


In [175]:
print(obj + obj2)

0     7.0
1     9.0
2    11.0
3    13.0
4     NaN
dtype: float64


In [176]:
print(obj - obj2)

0   -5.0
1   -5.0
2   -5.0
3   -5.0
4    NaN
dtype: float64


In [177]:
print(obj * obj2)

0     6.0
1    14.0
2    24.0
3    36.0
4     NaN
dtype: float64


In [178]:
print(obj / obj2)

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4         NaN
dtype: float64


In [179]:
print(obj // obj2)

0    0.0
1    0.0
2    0.0
3    0.0
4    NaN
dtype: float64


In [180]:
print(obj % obj2)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64


### Series 산술 메소드 : add, sub, mul, div, …

In [191]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
print(a)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64


In [193]:
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(b)

a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64


In [194]:
a.add(b)

a    2.0
b    NaN
c    NaN
d    NaN
e    NaN
dtype: float64

In [195]:
a.add(b, fill_value=0)

a    2.0
b    1.0
c    1.0
d    1.0
e    NaN
dtype: float64

In [196]:
a.sub(b, fill_value=0)

a    0.0
b    1.0
c    1.0
d   -1.0
e    NaN
dtype: float64

In [197]:
a.mul(b, fill_value=0)

a    1.0
b    0.0
c    0.0
d    0.0
e    NaN
dtype: float64

In [198]:
a.div(b, fill_value=0)

a    1.000000
b         inf
c         inf
d    0.000000
e         NaN
dtype: float64

## Series 메소드 : append()

In [202]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
print(a)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64


In [203]:
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(b)

a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64


In [204]:
a.append(b)

a    1.0
b    1.0
c    1.0
d    NaN
a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

In [212]:
a.append(b, verify_integrity=True)

ValueError: Indexes have overlapping values: Index(['a', 'b', 'd'], dtype='object')

In [213]:
a_re = pd.Series([1,2,3],index=['a','b','c'])
b_re = pd.Series([1,2,3],index=['d','e','f'])

In [215]:
a_re.append(b_re, verify_integrity=True)

a    1
b    2
c    3
d    1
e    2
f    3
dtype: int64

## Series 메소드 : count(), mode()

In [220]:
?np.random

In [228]:
rndNum = np.random.rand(5); print(list(rndNum))

[0.08605877977375265, 0.0836999233446768, 0.7493416744335958, 0.8339049337576254, 0.9962755869227065]


In [235]:
rndInt = np.random.randint(10, size=5)
print(rndInt)

[4 9 9 0 8]


In [236]:
obj = pd.Series(rndInt)

In [237]:
obj2 = pd.Series(index=set(rndInt)) # values data는 미정의

In [238]:
obj3 = pd.Series(index=list(rndInt))

In [243]:
print(obj,'\n');print(obj2,'\n');print(obj3)

0    4
1    9
2    9
3    0
4    8
dtype: int64 

0   NaN
9   NaN
4   NaN
8   NaN
dtype: float64 

4   NaN
9   NaN
9   NaN
0   NaN
8   NaN
dtype: float64


In [244]:
obj.mode() # value 중 가장 많은 값, Series type으로 return

0    9
dtype: int64

In [245]:
obj.count()

5

In [246]:
obj2.count()

0

In [248]:
obj2.at[9] = 3; obj2

0    NaN
9    3.0
4    NaN
8    NaN
dtype: float64

In [249]:
obj2.count()

1

## Series 평균 / 표준편차 / 분산 : mean, std, var, describe

In [253]:
rndInt = np.random.randn(5); rndInt

array([ 2.25842548, -0.14045925,  0.27953796,  1.47455769, -2.08057497])

In [254]:
obj = pd.Series(rndInt)
print(obj)

0    2.258425
1   -0.140459
2    0.279538
3    1.474558
4   -2.080575
dtype: float64


In [255]:
obj.mean()

0.35829738314746207

In [256]:
obj.sum() / len(obj)

0.35829738314746207

In [257]:
obj.std()

1.662797603586235

In [202]:
np.sqrt(((obj - obj.mean())**2).sum()/(len(obj)-1))

0.72489697817189913

In [203]:
obj.var()

0.5254756289627508

In [204]:
((obj - obj.mean())**2).sum()/(len(obj)-1)

0.5254756289627508

In [258]:
obj.describe()

count    5.000000
mean     0.358297
std      1.662798
min     -2.080575
25%     -0.140459
50%      0.279538
75%      1.474558
max      2.258425
dtype: float64

## Series 문자열 describe, unique

In [259]:
sentence = list('Good morning Welcome to Python Training')
print(sentence)

['G', 'o', 'o', 'd', ' ', 'm', 'o', 'r', 'n', 'i', 'n', 'g', ' ', 'W', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 'P', 'y', 't', 'h', 'o', 'n', ' ', 'T', 'r', 'a', 'i', 'n', 'i', 'n', 'g']


In [260]:
obj = pd.Series(sentence)
print(obj)

0     G
1     o
2     o
3     d
4      
5     m
6     o
7     r
8     n
9     i
10    n
11    g
12     
13    W
14    e
15    l
16    c
17    o
18    m
19    e
20     
21    t
22    o
23     
24    P
25    y
26    t
27    h
28    o
29    n
30     
31    T
32    r
33    a
34    i
35    n
36    i
37    n
38    g
dtype: object


In [261]:
obj.describe()

count     39
unique    19
top        o
freq       6
dtype: object

In [262]:
obj.unique()

array(['G', 'o', 'd', ' ', 'm', 'r', 'n', 'i', 'g', 'W', 'e', 'l', 'c',
       't', 'P', 'y', 'h', 'T', 'a'], dtype=object)

## Series 일부 데이터 확인 : head, tail

In [218]:
sentence = list('Good morning Welcome to Python Training')
obj = pd.Series(sentence)

In [219]:
obj.tail()

34    i
35    n
36    i
37    n
38    g
dtype: object

In [220]:
obj.head()

0    G
1    o
2    o
3    d
4     
dtype: object

In [221]:
obj.head(n=10)

0    G
1    o
2    o
3    d
4     
5    m
6    o
7    r
8    n
9    i
dtype: object

## Series 비교 : any, all

In [263]:
obj = pd.Series([0.1, 0.25, 0.5, 0.75, 1])

In [264]:
obj.all()

True

In [265]:
obj.any()

True

In [266]:
(obj>0.5)

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [237]:
(obj>0.5).all()

False

In [238]:
(obj>0.5).any()

True

In [279]:
obj = pd.Series([0, 0.25, 0.5, 0.75, 1])

In [280]:
(obj==True)

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [281]:
obj.all()

False

In [282]:
obj.any()

True

## Series 동일 여부 : equals

In [283]:
obj = pd.Series([0.1, 0.25, 0.5, 0.75, 1])
print(obj)

0    0.10
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


In [284]:
(obj+obj).equals(obj)

False

In [285]:
(obj+obj).equals(obj*2)

True

In [286]:
(obj+obj) == (obj*2)

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [287]:
((obj+obj) == (obj*2)).all()

True

## Series 원소 존재 확인 : empty

In [288]:
obj = pd.Series([0.1, 0.25, 0.5, 0.75, 1])
print(obj)
obj.empty

0    0.10
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


False

In [289]:
obj = pd.Series(index=['a','b','c'])
print(obj)
obj.empty

a   NaN
b   NaN
c   NaN
dtype: float64


False

In [290]:
obj = pd.Series()
print(obj)
obj.empty

Series([], dtype: float64)


True