## The N-Dimensional array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print('값: ', a, '차원: ', a.ndim)

값:  [1 2 3] 차원:  1


In [5]:
a = np.array([[1,2,3],[4,5,6]])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
list1 = [1,2,3]
list2 = [4,5,6]

In [11]:
x = np.array([list1,list2],dtype=np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [29]:
x = np.array([[1,2,3],[4,5,6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
type(x)

numpy.ndarray

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [13]:
x.shape

(2, 3)

In [8]:
x.dtype

dtype('int32')

In [15]:
x.size

6

In [16]:
x.itemsize

4

In [17]:
x.strides

(12, 4)

In [18]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [19]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [9]:
x.ndim

2

In [20]:
# The element of x in the *second* row, *third* column, namely, 6.
x[1, 2]

6

In [21]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [22]:
y[0] = 9 # this also changes the corresponding element in x
y

array([9, 5], dtype=int32)

In [23]:
type(y)

numpy.ndarray

In [25]:
tuple(y)

(9, 5)

In [26]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [14]:
x.T

array([[1, 4],
       [9, 5],
       [3, 6]], dtype=int32)

In [30]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [31]:
x.itemset((1,2),1)

In [32]:
x

array([[1, 2, 3],
       [4, 5, 1]], dtype=int32)

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]); a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## ndarray Inspecting

In [ ]:
import numpy as np

In [50]:
tuple_for_array = (3,3,2,2)
array_a = np.ndarray(tuple_for_array); print(array_a)

[[[[0.00000000e+000 4.33779560e-311]
   [8.89318163e-323 0.00000000e+000]]

  [[2.12199579e-314 1.16096346e-028]
   [1.04857803e-142 1.16467185e-028]]

  [[1.30354301e-076 2.62395837e+179]
   [1.81152935e-152 1.39804065e-076]]]


 [[[1.18295070e-076 8.94279358e+130]
   [1.72371836e-047 2.74010398e-057]]

  [[9.11160143e+130 3.12075289e-033]
   [7.25416361e-043 8.09244733e-153]]

  [[9.95135518e-043 9.14758644e+140]
   [4.85124939e-086 1.39838857e-076]]]


 [[[8.53716629e+136 4.62882712e-072]
   [2.52904806e-052 8.49176982e+136]]

  [[8.54511033e-072 4.08340567e+179]
   [1.81152936e-152 8.60954358e-043]]

  [[3.57280233e-062 7.78045999e-143]
   [1.58718589e-319 2.50320809e-308]]]]


In [33]:
arr = np.ndarray((5,3,2))

In [34]:
print(arr)

[[[ 0.00000000e+000 -2.68678931e+154]
  [ 1.08694442e-322  0.00000000e+000]
  [ 2.12199579e-314  5.02034658e+175]]

 [[ 4.76326335e-038  2.61017377e-057]
  [ 1.00082750e+165  2.87973393e+180]
  [ 1.47763641e+248  1.16096346e-028]]

 [[ 7.69165785e+218  1.35617292e+248]
  [ 3.39014783e+175  1.18784868e-075]
  [ 2.52823241e-052  6.48853762e+169]]

 [[ 4.30714220e-096  6.32299154e+233]
  [ 6.48224638e+170  5.22411352e+257]
  [ 5.74020278e+180  8.37174974e-144]]

 [[ 1.41529402e+161  9.16651763e-072]
  [ 5.38099907e+097  6.38997121e-067]
  [ 3.58901542e+126 -1.73060096e-077]]]


In [24]:
arr.shape

(5, 3, 2)

In [25]:
arr.ndim

3

In [26]:
arr.dtype

dtype('float64')

In [27]:
arr.dtype.name

'float64'

In [28]:
arr.size

30

## ndarray
### ndarray 차원

In [53]:
import numpy as np
a = np.array(0)
print('np.array(0)는 {} 값을 갖는 {} 타입의 {} 차원'.format(a, type(a), a.ndim))      

np.array(0)는 0 값을 갖는 <class 'numpy.ndarray'> 타입의 0 차원


In [21]:
a = np.array([1,2,3])
print('값:',a, '/ 차원:',a.ndim)

값: [1 2 3] / 차원: 1 int64


In [19]:
a = np.array([[1,2,3],[4,5,6]])
print('값:',a, '/ 차원:',a.ndim)

값: [[1 2 3]
 [4 5 6]] / 차원: 2


In [20]:
a = np.array( [ [[1,2,3],[4,5,6]], 
               [[1,2,3],[4,5,6]] ] )
print('값:',a, '/ 차원:',a.ndim)

값: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] / 차원: 3


### ndarray 생성

In [15]:
a1 = np.array([1,2,3,4,5])
print(a1, type(a1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [20]:
a2 = np.ndarray((2,2))
print(a2, type(a2))

[[  6.92022935e-310   6.92022935e-310]
 [  6.92022409e-310   6.92022409e-310]] <class 'numpy.ndarray'>


In [17]:
a3 = np.ones(3)
print(a3, type(a3))
a31 = np.ones((3,3))
print(a31, type(a31))

[ 1.  1.  1.] <class 'numpy.ndarray'>
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] <class 'numpy.ndarray'>


In [25]:
a4 = np.zeros(3)
print(a4, type(a4))
a41 = np.zeros((3,3))
print(a41, type(a41))

[ 0.  0.  0.] <class 'numpy.ndarray'>
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] <class 'numpy.ndarray'>


In [12]:
a5 = np.empty(3)
print(a5, type(a5))
a51 = np.empty((3,3))
print(a51, type(a51))

[  6.92022935e-310   4.67826868e-310   1.58101007e-322] <class 'numpy.ndarray'>
[[  6.92022935e-310   4.67826870e-310   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  7.06652082e-096   7.05479222e-308   3.95252517e-322]] <class 'numpy.ndarray'>


In [27]:
a6 = np.eye(3)
print(a6, type(a6))
a6 = np.eye(3, k=1)
print(a6, type(a6))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] <class 'numpy.ndarray'>
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]] <class 'numpy.ndarray'>


In [28]:
a7 = np.identity(3)
print(a7, type(a7))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] <class 'numpy.ndarray'>


In [29]:
a8 = np.linspace(1,5,10)
print(a8, type(a8))

[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ] <class 'numpy.ndarray'>


In [30]:
a9 = np.arange(1,10)
print(a9, type(a9))
a91 = np.arange(10)
print(a91, type(a91))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [31]:
a10 = np.float64([1,2,3])
print(a10, type(a10))

[ 1.  2.  3.] <class 'numpy.ndarray'>


In [32]:
a10 = np.int32([1,2,3])
print(a10, type(a10))

[1 2 3] <class 'numpy.ndarray'>


In [33]:
a11 = np.random.randn(3)
print(a11,type(a11))
a11 = np.random.rand(2,3)
print(a11,type(a11))
a11 = np.random.randint(1,99,size=6)
print(a11,type(a11))
a11 = np.random.ranf(3)
print(a11,type(a11))
a11 = np.random.random_sample(3)
print(a11,type(a11))
a11 = np.random.random(3)
print(a11,type(a11))

[ 1.88576026  0.62513821 -0.24684692] <class 'numpy.ndarray'>
[[ 0.42634603  0.10531788  0.88228211]
 [ 0.01707417  0.37577093  0.97184952]] <class 'numpy.ndarray'>
[84 56 87 90 33 50] <class 'numpy.ndarray'>
[ 0.90671941  0.98058635  0.25551313] <class 'numpy.ndarray'>
[ 0.79296798  0.87718523  0.29154009] <class 'numpy.ndarray'>
[ 0.98335612  0.44667824  0.53108699] <class 'numpy.ndarray'>


### ndarray 형변환

In [34]:
sample_list = [1,2,3,4,5,6]
trans_nd = np.asarray(sample_list)
print(trans_nd)
print(type(sample_list), type(trans_nd))

[1 2 3 4 5 6]
<class 'list'> <class 'numpy.ndarray'>


### ndarray loop

In [21]:
loop_ex = np.array([[1,2,3],[4,5,6]])
loop_ex1 = loop_ex * 4 + 1
print('loop_ex :',loop_ex)
print('loop_ex1:',loop_ex1)

loop_ex : [[1 2 3]
 [4 5 6]]
loop_ex1: [[ 5  9 13]
 [17 21 25]]


### ndarray 접근

In [35]:
nd1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd1)
print('[1] row get :', nd1[1])
print('[:,1] column get :', nd1[:,1])
print('[1:,:2] get :', nd1[1:,:2])
print('(1,2) row*column get :', nd1[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1] row get : [4 5 6]
[:,1] column get : [2 5 8]
[1:,:2] get : [[4 5]
 [7 8]]
(1,2) row*column get : 6


In [36]:
nd2 = np.random.randint(1,99,10)
print(nd2)
print(nd2[3:5])
nd2[3:5] = 11
print(nd2)

[58 85 98 13 47 48 78 94 45 26]
[13 47]
[58 85 98 11 11 48 78 94 45 26]


In [37]:
nd1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd1)
print('[1:,:2] get :', nd1[1:,:2])
nd1[1:,:2] = 0
print(nd1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1:,:2] get : [[4 5]
 [7 8]]
[[1 2 3]
 [0 0 6]
 [0 0 9]]


### ndarray 조건 조회

In [38]:
nd3 = np.random.randint(1,99,10)
print(nd3)
nd31 = nd3 > 50
print(nd31)
print(nd3[nd31])

print(nd3[nd3 > 50])

nd3[nd3 > 50] = 0
print(nd3)

[25 34 12 88 72 65 35 26 78 26]
[False False False  True  True  True False False  True False]
[88 72 65 78]
[88 72 65 78]
[25 34 12  0  0  0 35 26  0 26]


### ndarray 사칙연산

In [39]:
nd4 = np.array([[1,2],[3,4]])
nd5 = np.array([[5,6],[7,8]])
print(nd4, type(nd4))
print(nd5, type(nd5))
print(nd4+nd5)
print(nd5-nd4)
print(nd4*nd5)
print(nd4/nd5)

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
[[5 6]
 [7 8]] <class 'numpy.ndarray'>
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


### matrix 사칙연산

In [56]:
nd4 = np.matrix([[1,2],[3,4]])
nd5 = np.matrix([[5,6],[7,8]])
print(nd4, type(nd4))
print(nd5, type(nd5))
print(nd4+nd5)
print(nd5-nd4)
print(nd4*nd5)
print(nd4/nd5)

[[1 2]
 [3 4]] <class 'numpy.matrixlib.defmatrix.matrix'>
[[5 6]
 [7 8]] <class 'numpy.matrixlib.defmatrix.matrix'>
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[19 22]
 [43 50]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### ndarray, matrix dot 연산

In [41]:
nd4 = np.array([[1,2],[3,4]])
nd5 = np.array([[5,6],[7,8]])
print(nd4)
print(nd5)
print(nd4.dot(nd5))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [42]:
nd4 = np.matrix([[1,2],[3,4]])
nd5 = np.matrix([[5,6],[7,8]])
print(nd4)
print(nd5)
print(nd4.dot(nd5))
print(nd4*(nd5))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### T(전치)

In [55]:
nd4 = np.array([[1,2],[3,4]])
print(nd4)
print(nd4.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### axis - 2 dim sum example

In [43]:
nd4 = np.array([[1,2],[3,4]])
print(nd4)
print('sum :',np.sum(nd4))
print('axis 0 sum :',np.sum(nd4, axis=0))
print('axis 1 sum :',np.sum(nd4, axis=1))

[[1 2]
 [3 4]]
sum : 10
axis 0 sum : [4 6]
axis 1 sum : [3 7]


### axis - 3 dim sum example

In [80]:
nd6 = np.arange(0, 24).reshape([2,3,4])
nd6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
nd6.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [82]:
nd6.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [83]:
nd6.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [45]:
nd6 = np.arange(1,9).reshape(2,2,2)
print(nd6)
print('sum :',np.sum(nd6))
print('axis 0 sum :',np.sum(nd6, axis=0))
print('axis 1 sum :',np.sum(nd6, axis=1))
print('axis 2 sum :',np.sum(nd6, axis=2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
sum : 36
axis 0 sum : [[ 6  8]
 [10 12]]
axis 1 sum : [[ 4  6]
 [12 14]]
axis 2 sum : [[ 3  7]
 [11 15]]


### inner 함수

In [8]:
nd7 = np.array( [1,2,3] )
nd8 = np.array( [4,5,6] )
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print('inner :',np.inner(nd7,nd8))
print('dot T :',np.dot(nd7,nd8))

[1 2 3] (3,)
[4 5 6] (3,)
inner : 32
dot T : 32


In [11]:
nd7 = np.array( [ [1,2,3], [4,5,6] ] )
nd8 = np.array( [ [4,3,2], [1,5,6], [4,3,2], [1,5,6] ] )
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print('inner :',np.inner(nd7,nd8))
print('second T :',np.dot(nd7,nd8.T))

[[1 2 3]
 [4 5 6]] (2, 3)
[[4 3 2]
 [1 5 6]
 [4 3 2]
 [1 5 6]] (4, 3)
inner : [[16 29 16 29]
 [43 65 43 65]]
second T : [[16 29 16 29]
 [43 65 43 65]]


### outer

In [12]:
nd7 = np.array( [1,2,3] )
nd8 = np.array( [4,5,6] )
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print('outer :',np.outer(nd7,nd8))
print('cross :',np.cross(nd7,nd8))

[1 2 3] (3,)
[4 5 6] (3,)
outer : [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
cross : [-3  6 -3]


In [13]:
nd7 = np.array( [ [1,2,3], [4,5,6] ] )
nd8 = np.array( [ [4,3,2], [1,5,6] ] )
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print('outer :',np.outer(nd7,nd8))
print('cross :',np.cross(nd7,nd8))

[[1 2 3]
 [4 5 6]] (2, 3)
[[4 3 2]
 [1 5 6]] (2, 3)
outer : [[ 4  3  2  1  5  6]
 [ 8  6  4  2 10 12]
 [12  9  6  3 15 18]
 [16 12  8  4 20 24]
 [20 15 10  5 25 30]
 [24 18 12  6 30 36]]
cross : [[ -5  10  -5]
 [  0 -18  15]]


### numpy 함수

In [14]:
nd9 = np.random.randint(-10,10,5)
print(nd9)
print(np.abs(nd9))
si = np.sign(nd9)
print(si)
print(np.abs(nd9) * si)

[-1  7  1  4 -4]
[1 7 1 4 4]
[-1  1  1  1 -1]
[-1  7  1  4 -4]


In [51]:
f1 = np.random.randint(1,10,5)
print(f1)
print(np.square(f1))
print(np.sqrt(f1))
print(np.power(f1, 3))
print(np.hypot(f1, np.square(f1)))

[5 2 8 2 4]
[25  4 64  4 16]
[ 2.23606798  1.41421356  2.82842712  1.41421356  2.        ]
[125   8 512   8  64]
[ 25.49509757   4.47213595  64.49806199   4.47213595  16.4924225 ]


In [52]:
f2 = np.random.randn(5)
f2 = f2*10
print(f2)
print(np.ceil(f2))
print(np.floor(f2))
print(np.rint(f2))

[  7.70897982  -4.47915609  12.79167955  -4.43478021  10.99406411]
[  8.  -4.  13.  -4.  11.]
[  7.  -5.  12.  -5.  10.]
[  8.  -4.  13.  -4.  11.]


In [53]:
f3 = np.random.randint(1,100,5)
f4 = np.random.randint(1,10,5)
print(f3)
print(f4)
print('add : ', np.add(f3,f4))
print('subtract : ', np.subtract(f3,f4))
print('multiply : ', np.multiply(f3,f4))
print('divide : ', np.divide(f3,f4))
print('mod : ', np.mod(f3,f4))

[83 93  8 83  7]
[2 1 3 6 4]
add :  [85 94 11 89 11]
subtract :  [81 92  5 77  3]
multiply :  [166  93  24 498  28]
divide :  [ 41.5         93.           2.66666667  13.83333333   1.75      ]
mod :  [1 0 2 5 3]


In [54]:
f5 = np.random. randint(0,5,5)
print(f5)
print(np.any(f5)) # True가 하나라도 존재
print(np.all(f5)) # 전체가 True가 아님 0 존재

[1 2 1 2 1]
True
True


In [55]:
f5 = np.random. randint(0,5,5)
f6 = np.random. randint(0,5,5)
print(f5)
print(f6)
f7 = np.equal(f5,f6)
print(f7)
print(np.any(f7)) # True가 하나라도 존재
print(np.all(f7)) # 전체가 True가 아님 0 존재

[1 3 4 1 1]
[0 4 1 2 2]
[False False False False False]
False
False


In [56]:
f8 = np.random.randint(-10,10,10)
print(f8)
print(np.where(f8 == 0, 0, np.where(f8 > 0, 1, -1)))
print(np.sign(f8))

[-2  3 -5 -4 -5 -8 -9  7 -9  6]
[-1  1 -1 -1 -1 -1 -1  1 -1  1]
[-1  1 -1 -1 -1 -1 -1  1 -1  1]


In [54]:
f9 = np.arange(9.).reshape(3, 3)
print(f9)
print(np.where( f9 > 5 ))
print(x[np.where( f9 > 3.0 )])  # Note: result is 1D. 
print(np.where(f9 < 5, f9, -1) )  # Note: broadcasting. 

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([2, 2, 2]), array([0, 1, 2]))


IndexError: index 2 is out of bounds for axis 0 with size 2

In [73]:
f10 = np.random.randint(1,10,5)
f11 = np.random.randint(1,5,3)
print(f10)
f10u = np.unique(f10)
print(f10u)
print(f11)
print('in1d :',np.in1d(f11,f10u))
print('union1d :',np.union1d(f11,f10u))
print('intersect1d :',np.intersect1d(f11,f10u))
print('setdiff1d :',np.setdiff1d(f11,f10u))
print('setxor1d :',np.setxor1d(f11,f10u))

[6 6 9 9 3]
[3 6 9]
[3 1 4]
in1d : [ True False False]
union1d : [1 3 4 6 9]
intersect1d : [3]
setdiff1d : [1 4]
setxor1d : [1 4 6 9]


In [104]:
r1 = np.arange(1,7).reshape(2,3)
print(r1)
print('flatten :', r1.flatten())
print('ravel :', r1.ravel())
print('reshape(6) :', r1.reshape(6))
print('reshape(3,2) :', r1.reshape(3,2))

[[1 2 3]
 [4 5 6]]
flatten : [1 2 3 4 5 6]
ravel : [1 2 3 4 5 6]
reshape(6) : [1 2 3 4 5 6]
reshape(3,2) : [[1 2]
 [3 4]
 [5 6]]


In [140]:
c2 = np.arange(1,5)
c3 = np.arange(5,9)
c4 = np.arange(9,11)
c5 = np.array((c2,c3,c4))
print(c2)
print(c3)
print(c4)
print(c5)
print(np.concatenate((c2,c3,c4)))
print(np.concatenate(c5))

[1 2 3 4]
[5 6 7 8]
[ 9 10]
[array([1, 2, 3, 4]) array([5, 6, 7, 8]) array([ 9, 10])]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [141]:
c6 = np.concatenate(c5)
c7 = c6 + 5
print(c6)
print(c7)
c6 = c6.reshape(2,5)
c7 = c7.reshape(2,5)
print(c6)
print(c7)


print(np.concatenate((c6,c7)))
print(np.concatenate((c6,c7),axis=1))

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 6  7  8  9 10 11 12 13 14 15]]


## array save and load

In [40]:
save_arr = np.ndarray((5,2))
print(save_arr)

[[  6.92022935e-310   4.67826867e-310]
 [  0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000]
 [  6.92022935e-310   1.63041663e-322]
 [  4.67826870e-310   4.67826867e-310]]


In [61]:
np.save('./save_arr',save_arr)

In [62]:
load_arr = np.load('./save_arr.npy')

In [63]:
load_arr

array([[  6.92022935e-310,   4.67826867e-310],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  6.92022935e-310,   1.63041663e-322],
       [  4.67826870e-310,   4.67826867e-310]])

In [64]:
save_arr1 = np.ndarray((5,2))
save_arr2 = np.ndarray((5,2))
print(save_arr1)
print(save_arr2)

[[  6.92022935e-310   4.67826867e-310]
 [  0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000]
 [  6.92022935e-310   1.63041663e-322]
 [  4.67826870e-310   4.67826867e-310]]
[[  6.92022935e-310   4.67826859e-310]
 [  0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000]
 [  3.16202013e-322   3.95252517e-322]
 [  4.67826859e-310   0.00000000e+000]]


In [67]:
np.savez('./save_arr',save_arr1, save_arr2)

In [69]:
load_arr = np.load('./save_arr.npz')
load_arr.files

['arr_0', 'arr_1']

In [72]:
load_arr['arr_0']

array([[  6.92022935e-310,   4.67826867e-310],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  6.92022935e-310,   1.63041663e-322],
       [  4.67826870e-310,   4.67826867e-310]])